### Consider the below code to answer further questions:

### import numpy as np
### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
### array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
'''
The list_ is a python list and the array_list is a numpy array. We can print the data type of both the array using type function 
as shown below:
'''

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

print("Data type of list_ is ", type(list_))

print("Data type of array_list is ", type(array_list))

Data type of list_ is  <class 'list'>
Data type of array_list is  <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [9]:
'''
Yes there will be a change in variable type of the array_list as the data type of the list will be converted into integer
and those will be elements of numpy array.
'''
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype = int)

# Print the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Consider the below code to answer further questions:
### import numpy as np
### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
### num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Finding the shape of numpy array
print("The shape of num_list is ", np.shape(num_array))


# Finding the size of numpy array
print("The size of num_list is ", np.size(num_array))

The shape of num_list is  (2, 3)
The size of num_list is  6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [15]:
# Creating the zero matrix

print("Zero matrix of shape (3,3) is as below:")
print(np.zeros((3,3)))

Zero matrix of shape (3,3) is as below:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
# Creating identity matrix
print("Identity matrix of shape (5,5) is ")

print(np.eye(5))

Identity matrix of shape (5,5) is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
